name: Lint

on:
 pull_request:
    branches:
      - main

jobs:
 run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install ruff

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          ruff: true
          ruff_auto_fix: true
